storage:
  host: "$CASSANDRA_HOSTS"
  key_space: "$CASSANDRA_KEY_SPACE"
  username: "$CASSANDRA_USERNAME"
  password: "$CASSANDRA_PASSWORD"

bind_socket: "$BIND_SOCKET"
collector_endpoint: "$COLLECTOR_ENDPOINT"
