CASSANDRA_HOSTS: "localhost"
CASSANDRA_KEY_SPACE: "easytracer"
CASSANDRA_USERNAME: ""
CASSANDRA_PASSWORD: ""

BIND_SOCKET: "/var/run/easytracer.sock"
COLLECTOR_ENDPOINT: "http://127.0.0.1:6790/v1/collect"
